return {
  -- { "AndreM222/copilot-lualine" },
  -- {
  -- 	"nvim-lualine/lualine.nvim",
  -- 	event = "VeryLazy",
  -- 	opts = function(_, opts)
  -- 		table.insert(
  -- 			opts.sections.lualine_x,
  -- 			2,
  -- 			LazyVim.lualine.status(LazyVim.config.icons.kinds.Copilot, function()
  -- 				local clients = package.loaded["copilot"]
  -- 						and LazyVim.lsp.get_clients({ name = "copilot", bufnr = 0 })
  -- 					or {}
  -- 				if #clients > 0 then
  -- 					local status = require("copilot.api").status.data.status
  -- 					return (status == "InProgress" and "pending") or (status == "Warning" and "error") or "ok"
  -- 				end
  -- 			end)
  -- 		)
  -- 	end,
  -- },
  -- {
  --   "zbirenbaum/copilot.lua",
  --   enable = false,
  --   cmd = "Copilot",
  --   build = ":Copilot auth",
  --   event = "InsertEnter",
  --   config = function()
  --     require("copilot").setup({
  --       filetypes = { yaml = true, sh = true },
  --       suggestion = { auto_trigger = true },
  --     })
  --   end,
  -- },
}
